name: PR build

on:
  pull_request:

jobs:
  docker-pr:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/manics/action-major-minor-tag-calculator-test
      - name: Get other tags
        id: gettags
        uses: manics/action-major-minor-tag-calculator@noref
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          prefix: "manics/action-major-minor-tag-calculator-test:"

      # https://github.com/docker/build-push-action

      - name: Display tags
        run: echo "${{ steps.gettags.outputs.tags }}"
