name: Docker build

on:
  - push

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/manics/action-major-minor-tag-calculator-test
      - name: Get other tags
        id: gettags
        uses: manics/action-major-minor-tag-calculator-test@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/build-push-action
      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          repository: action-major-minor-tag-calculator-test
          tags: ${{ join(fromJson(steps.gettags.outputs.tags)) }}
          push: false

      - name: List Docker images
        run: docker image ls
