name: Docker build

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/manics/action-major-minor-tag-calculator-test
      - name: Get other tags
        id: gettags
        uses: manics/action-major-minor-tag-calculator@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          prefix: "manics/action-major-minor-tag-calculator-test:"

      # https://github.com/docker/build-push-action

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ join(fromJson(steps.gettags.outputs.tags)) }}
          push: true

      - name: List Docker images
        run: docker image ls
