name: Docker build

on:
  pull_request:
  push:
    # Remove branches if you only want tags
    branches:
      - "*"
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/manics/action-major-minor-tag-calculator-test
      - name: Get other tags
        id: gettags
        uses: manics/action-major-minor-tag-calculator@branchRegex
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          prefix: "manics/action-major-minor-tag-calculator-test:"
          branchRegex: "^[^/]+$"

      - name: Display tags
        run: echo "${{ steps.gettags.outputs.tags }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ join(fromJson(steps.gettags.outputs.tags)) }}
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
